"""Add session_id to exercise_log

Revision ID: 50332ba23f0f
Revises: 76eb4d91fe9d
Create Date: 2025-03-24 14:59:44.821065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50332ba23f0f'
down_revision = '76eb4d91fe9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
